[package]
name = "csgames-projet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.19.1"
futures = "0.3.30"
bytemuck = "1.14.3"